service: serverless-name-generator

package:
  exclude:
    - .circleci
    - coverage

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 4
  versionFunctions: false # optional, default is true

plugins:
  - serverless-offline

functions:
  generate:
    handler: handler.handler # required, handler set in AWS Lambda
    description: Generates unique and memorable names # optional, Description to publish to AWS
    events:
      - http:
          path: generate
          method: get
          cors: true
